import 'package:residuum_content/content.dart';
import 'package:test/test.dart';

/// A whole version-1 document, lifted from the golden this branch inherited.
///
/// Captured BEFORE the version-2 goldens were written, which is the only order
/// that makes this test mean anything: a fixture regenerated by the new encoder
/// would prove the new encoder agrees with itself, and nothing at all about the
/// saves already on players' phones.
const String _versionOneTown =
    '{"version":1,"active":"hero-1","heroes":{"hero-1":{"label":"He'
    'ro 1","profile":{"hp":14,"gold":30,"bankedGold":120,"worldSeed'
    '":"9007199254740993","visit":3,"equipment":{"mainHand":{"id":"'
    'drop-3","base":"war-axe","rarity":"rare","affixes":["keen","of'
    '-embers"]}},"inventory":[{"id":"kit-2","base":"healing-potion"'
    ',"rarity":"common","affixes":[]}],"bank":[{"id":"drop-1","base'
    '":"iron-sword","rarity":"common","affixes":[]}],"skills":{"arm'
    's":{"level":4,"xp":2},"might":{"level":0,"xp":0},"bulwark":{"l'
    'evel":0,"xp":0},"fleetfoot":{"level":0,"xp":0}}},"run":null,"d'
    'ungeon":null,"inside":false,"campDay":null,"world":{"at":"nort'
    'hgate","home":"northgate","day":30,"discovered":["crypt","nort'
    'hgate","stonebridge"],"journey":null},"merchant":{"bought":[],'
    '"sold":[],"town":null}}}}';

void main() {
  group('the version gate', () {
    test('refuses a whole version-1 document by number', () {
      // arrange
      const document = _versionOneTown;

      // act
      final read = decodeSave(document);

      // assert - refused as a version rather than misread as a shape, so the
      // fallback chain above the codec can offer a new hero instead
      expect(read, isA<SaveFailure>());
      expect((read as SaveFailure).reason, contains('version 1'));
      expect(read.reason, contains('version $saveVersion'));
    });

    test('refuses it before reading a single field of it', () {
      // arrange - the version is right at the front and everything after it is
      // nonsense, so a gate that read the body first would fail differently
      const document = '{"version":1,"heroes":"nonsense"}';

      // act
      final read = decodeSave(document);

      // assert
      expect(read, isA<SaveFailure>());
      expect((read as SaveFailure).reason, contains('version 1'));
    });

    test('this build writes version two', () {
      // arrange
      // act
      const written = saveVersion;

      // assert - the last sanctioned break: v2 freezes at the first shipped
      // build, and every pre-M3M hero is refused by design
      expect(written, 2);
    });
  });
}
