import 'package:residuum_content/content.dart';
import 'package:test/test.dart';

/// A whole version-1 document, lifted from the golden this branch inherited.
///
/// Captured BEFORE the version-2 goldens were written, which is the only order
/// that makes this test mean anything: a fixture regenerated by the new encoder
/// would prove the new encoder agrees with itself, and nothing at all about the
/// saves already on players' phones.
const String _versionOneTown =
    '{"version":1,"active":"hero-1","heroes":{"hero-1":{"label":"He'
    'ro 1","profile":{"hp":14,"gold":30,"bankedGold":120,"worldSeed'
    '":"9007199254740993","visit":3,"equipment":{"mainHand":{"id":"'
    'drop-3","base":"war-axe","rarity":"rare","affixes":["keen","of'
    '-embers"]}},"inventory":[{"id":"kit-2","base":"healing-potion"'
    ',"rarity":"common","affixes":[]}],"bank":[{"id":"drop-1","base'
    '":"iron-sword","rarity":"common","affixes":[]}],"skills":{"arm'
    's":{"level":4,"xp":2},"might":{"level":0,"xp":0},"bulwark":{"l'
    'evel":0,"xp":0},"fleetfoot":{"level":0,"xp":0}}},"run":null,"d'
    'ungeon":null,"inside":false,"campDay":null,"world":{"at":"nort'
    'hgate","home":"northgate","day":30,"discovered":["crypt","nort'
    'hgate","stonebridge"],"journey":null},"merchant":{"bought":[],'
    '"sold":[],"town":null}}}}';

/// A whole version-2 document, captured off the version-2 golden BEFORE any
/// codec of this unit was touched — see the commit that added it, which lands
/// before the commit that bumped the version.
///
/// The order is the whole of what makes this test mean anything. A string
/// regenerated by the version-3 encoder would prove that encoder agrees with
/// itself and nothing at all about the documents already written; this one was
/// a document the build loaded, and now it is a document the build refuses.
///
/// What makes it unreadable is the skills block: it names seven skills, and this
/// build has nine. [decodeSkills] builds only from the document, so it would
/// hand back a hero with Herbcraft and Blacksmith silently at zero — the quiet
/// degradation the never-repair rule forbids, which is why the gate is a version
/// number and not a field check.
const String _versionTwoTown =
    '{"version":2,"active":"hero-1","heroes":{"hero-1":{"label":"He'
    'ro 1","profile":{"hp":14,"gold":30,"bankedGold":120,"worldSeed'
    '":"9007199254740993","visit":3,"equipment":{"mainHand":{"id":"'
    'drop-3","base":"war-axe","rarity":"rare","affixes":["keen","of'
    '-embers"]}},"inventory":[{"id":"kit-2","base":"healing-potion"'
    ',"rarity":"common","affixes":[]}],"bank":[{"id":"drop-1","base'
    '":"iron-sword","rarity":"common","affixes":[]}],"skills":{"arm'
    's":{"level":4,"xp":2},"might":{"level":0,"xp":0},"bulwark":{"l'
    'evel":0,"xp":0},"fleetfoot":{"level":0,"xp":0},"wrath":{"level'
    '":2,"xp":3},"mending":{"level":0,"xp":0},"binding":{"level":0,'
    '"xp":0}},"knownSpells":["firebolt"]},"run":null,"dungeon":null'
    ',"inside":false,"campDay":null,"world":{"at":"northgate","home'
    '":"northgate","day":30,"discovered":["crypt","northgate","ston'
    'ebridge"],"journey":null},"merchant":{"bought":[],"sold":[],"t'
    'own":null}}}}';

void main() {
  group('the version gate', () {
    test('refuses a whole version-1 document by number', () {
      // arrange
      const document = _versionOneTown;

      // act
      final read = decodeSave(document);

      // assert - refused as a version rather than misread as a shape, so the
      // fallback chain above the codec can offer a new hero instead
      expect(read, isA<SaveFailure>());
      expect((read as SaveFailure).reason, contains('version 1'));
      expect(read.reason, contains('version $saveVersion'));
    });

    test('refuses it before reading a single field of it', () {
      // arrange - the version is right at the front and everything after it is
      // nonsense, so a gate that read the body first would fail differently
      const document = '{"version":1,"heroes":"nonsense"}';

      // act
      final read = decodeSave(document);

      // assert
      expect(read, isA<SaveFailure>());
      expect((read as SaveFailure).reason, contains('version 1'));
    });

    test('this build writes version three', () {
      // arrange
      // act
      const written = saveVersion;

      // assert - a sanctioned break, and deliberately not called the last one:
      // the version freezes at the first SHIPPED build, and the two dartdocs
      // that claimed finality before this were both wrong inside a milestone
      expect(written, 3);
    });
  });

  group('the version-two fixture', () {
    test('is refused by number, as the version-one one is', () {
      // arrange
      const document = _versionTwoTown;

      // act
      final read = decodeSave(document);

      // assert
      expect(read, isA<SaveFailure>());
      expect((read as SaveFailure).reason, contains('version 2'));
      expect(read.reason, contains('version $saveVersion'));
    });

    test('is refused whole, not read down to the field that broke', () {
      // arrange
      const document = _versionTwoTown;

      // act
      final read = decodeSave(document);

      // assert - the seven-skill block inside it is perfectly well formed, so a
      // decoder that checked shapes rather than the version would load this
      // hero and quietly give them two skills they never trained
      expect(read, isA<SaveFailure>());
      expect((read as SaveFailure).reason, isNot(contains('skill')));
    });
  });
}
